### ISSUE TITLE
Suggestion for a Gtk Theme variant

### ISSUE THREAD

**Issue by muneebusmani** [HimDek/Utterly-Sweet-Plasma#4]
i suggest you should add a gtk variant of this theme too, because gtk apps are not getting this theme applied even after following system theme, the window action buttons remain as the default breeze window decorations

**Comment by HimDek** [comment]
Contributors are welcome but don't want to work on it right now

**Comment by muneebusmani** [comment]
what's the process to do it? like doing it all over again?
